### PR TITLE
Add 'in_tempdir' function to run coderef in a tempdir

### PR DESCRIPTION
**Pull request by dagolden**
This implements the request in #7.

### CODE REVIEW

**Comment by kentfredric** [comment]
I kinda worry about the need for `wantarray`. I generally get the hair standing up on the back of my neck everywhere I see it used. Some of it I understand, but I also worry its a YAGNI which actually prevents us making better APIs later.

For instance, eval returning contents on success and undef on failure gets messy if you can't disambiguate between a literal eval and a failure eval, so a "passthrough" design there just allows people to shoot themselves easily.

Similarly, I wonder if a `wantarray`+ return from callback is wise, and it may limit us doing other things, like we may one day think

```
in_tempdir "somename" => sub { 

} or do {  
    custom failure handling to keep the test plan in sync
};
```

Could be a desirable pattern.

That, and the notion that returning a value from inside the sub seems very low on the list of things one wants to do here.

I would overall be much more comfortable with 

```perl
my $return; 
in_tempdir "name" => sub {
   <code>
   $return = 5;
};
```
Being the pattern required to get inner sub values returned. There's less hidden-context-footguns there to worry about.

**Comment by kentfredric** [comment]
Another thought: 

It may also be desirable to codify the logic in terms of

```perl
sub in_tempdir { 
    my $code = pop;
    my ( $name, $opthash ) = @_;
    
}
```
Which would allow people to not provide a name if they didn't need one.

```perl
in_tempdir(sub {
    ...
});
```

**Comment by dagolden** [comment]
All the `wantarray` does is let us pass through the caller's context.  The real questions are:
* is the return value of the code reference meaningful or not
* is there any meaningful value to return for the tempdir operation itself?

I have a hard time imagining a boolean outcome for the tempdir operation.  It succeeds or throws an error.  To quote a co-worker, "lets defy augury" and not worry about "someday we might change our minds".

Then if tempdir operations have no meaningful return, I see no reason not to just pass through the callback return value.  Making people use closures is not very user-friendly.  I've been down this road with Capture::Tiny.  People are going to want return values of their code-refs.  They're going to want to use function references (where they can't have closures) and get return values from them.

So I'm not swayed by your concerns there.

As for going without a name or adding in an options hash, this is a ::Tiny module.  I have no problem saying that the API comes in any color you want, as long as that color is black.

David

**Comment by ribasushi** [comment]
@dagolden Won't be able to look at any of this today (upcoming presentation), but would like to. If this can wait until tomorrow, I'll take a more thoughtful look.

**Comment by dagolden** [comment]
@ribasushi, it can wait

**Comment by shadowcat-mst** [comment]
@kentfredric the wantarray here is really just Context::Preserve - I don't find that particular use a big deal, just like I'm not upset that method modifiers have to do that :)

**Comment by shadowcat-mst** [comment]
Honestly ... if a return value isn't that useful, it's probably better not to have one. But 'that useful' is defined by use cases, and of course it's not immediately clear how people will end up using this.

I'm tempted to suggest 'no return value for the moment but then see if that turns out to be annoying', since it's possible to add but not remove that ... but equally it doesn't immediately strike me as *that* dangerous.

**Pull request closed without merging**
