### PR TITLE
Bumped required version of File::Path to 2.07

### PR DESCRIPTION
**Pull request by skirmess**
The remove_tree function was added in File::Path 2.06_06 (and is therefore not available in 2.01)

See [here](https://metacpan.org/changes/distribution/File-Path#L163).

### CODE REVIEW

**Comment by karenetheridge** [comment]
I think you mean s/Path::Tiny/File::Path/ (in Changes and the commit message)?

**Comment by skirmess** [comment]
Fixed the Changes file and the commit message. Thanks, @karenetheridge .

**Comment by xdg** [comment]
Dev release prereqs are sometimes a problem for some versions of the toolchain.  Could you please bump to 2.07?

**Comment by karenetheridge** [comment]
alternatively, numifying to "2.0606" should be ok too I think.

**Comment by skirmess** [comment]
I've bumped it to 2.07.

**Pull request merged**
